[tool.ruff]
exclude = [
    "migrations",
    "venv",
    ".venv",
]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = [
    "F", # Flake8
    "B", # Black
    "I", # isort
    "E", # error
    "W"  # warning
]
ignore = []
fixable = ["E", "W", "I"]
